apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-market-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=ghcr.io/rodneywells01/kubemarketapp
    argocd-image-updater.argoproj.io/app.update-strategy: digest
    argocd-image-updater.argoproj.io/app.allow-tags: regexp:^latest$
    argocd-image-updater.argoproj.io/app.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/app.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rodneywells01/KubeMarketApp
    targetRevision: master
    path: mychart
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-market-app
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
